#pragma once

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#undef MOUSEKEY_WHEEL_INTERVAL
#undef MOUSEKEY_WHEEL_MAX_SPEED

#define MOUSEKEY_WHEEL_TIME_TO_MAX 250
#define MOUSEKEY_WHEEL_INTERVAL 100
#define MOUSEKEY_WHEEL_MAX_SPEED 3

#undef TAPPING_TERM
#define TAPPING_TERM 200

//#define PERMISSIVE_HOLD
#define HOLD_ON_OTHER_KEY_PRESS

//#define TAPPING_TERM_PER_KEY
